name: .NET

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x 
    - name: Publish
      run: |
        dotnet publish -c Release -r win-x86 WEBCON.FormsGenerator.Presentation/ -o ./WEBCON.FormsGenerator.Presentation/Release
    - name: Deploy artifact
      uses: actions/upload-artifact@v4
      with:
        name: PublicForms
        path: |
          WEBCON.FormsGenerator.Presentation/Release/
